export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_PIZZAS = 'SET_PIZZAS';
export const SET_CATEGORY_BY_ID = 'SET_CATEGORY_BY_ID';
export const ADD_PIZZA_TO_CART = 'ADD_PIZZA_TO_CART';
export const REMOVE_ALL_PIZZAS = 'REMOVE_ALL_PIZZAS';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
